{
 "title": "FIAP Cloud Games — Observabilidade",
 "tags": [
  "fcg",
  "microservices"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latência p95 por Serviço",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, job) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95 {{job}}"
    }
   ]
  },
  {
   "title": "Requests por Segundo (por Serviço)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_requests_received_total[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Taxa de Erros 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_requests_received_total{code=~\"5..\"}[5m])) / sum by (job) (rate(http_requests_received_total[5m]))",
     "legendFormat": "Taxa de Erro {{job}}"
    }
   ]
  },
  {
   "title": "Requests por Status Code",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code, job) (rate(http_requests_received_total[5m]))",
     "legendFormat": "{{job}} - {{code}}"
    }
   ]
  }
 ]
}